---
# tasks file for images
- name: Pull nginx image
  command: docker pull nginx:alpine

- name: Pull php7 Image
  command: docker pull atracht/php7

- name: Pull MySQL Image
  command: docker pull mariadb

- name: Pull Redis Image
  command: docker pull redis

- name: Pull Varnish Image
  command: docker pull million12/varnish

- name: Docker compose start
  shell: docker-compose -f /docker/docker-compose.yml up -d
