php7:
    image: atracht/php7
    links:
        - mysql
        - redis
    volumes:
      - /www/php7/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
        - data
    ports:
        - 9000
nginx:
    image: nginx
    volumes:
        - /www/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /www/sites:/usr/share/nginx/sites
    volumes_from:
        - data
    links:
        - php7
    ports:
      - 8080
mysql:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - 127.0.0.1:3306:3306
    volumes:
        - /www/mysql/config:/etc/mysql/conf.d
varnish:
    image: million12/varnish
    volumes:
        - /www/varnish/default.vcl:/etc/varnish/default.vcl
    ports:
        - 80:80
    links:
        - nginx
redis:
    image: redis
data:
    image: busybox
    volumes:
        - /www/html:/usr/share/nginx/html
