php7:
    image: atracht/php7
    links:
        - mysql
    volumes:
      - /www/php7/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
        - data
    ports:
        - 9000
nginx:
    image: atracht/nginx
    volumes:
        - /www/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /www/sites:/usr/share/nginx/sites
    volumes_from:
        - data
    links:
        - php7
    ports:
      - 80:80
mysql:
    image: atracht/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - 127.0.0.1:3306:3306
data:
    image: busybox
    volumes:
        - /www/html:/usr/share/nginx/html
