---
# tasks file for firewall
- name: Allow SSH
  ufw: rule=allow port=22 proto=tcp

- name: Allow http
  ufw: rule=allow port=80 proto=tcp

- name: Allow https
  ufw: rule=allow port=443 proto=tcp

- name: Deny incoming
  ufw: policy=deny direction=incoming

- name: Allow outgoing
  ufw: policy=allow direction=outgoing

- name: Enable UFW
  ufw: state=enabled
